pipelines:
  default:
    - step:
        name: Sync github Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:kganapathi/crud_backend.git
          - cd crud_backend.git
          - git remote add google https://source.developers.google.com/p/profound-coda-368811/r/my-repository-hello-mrr
          - git push --all google