pipelines:
  default:
    - step:
        name: Sync github Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:kganapathi/crud_backend.git
          - cd crud_backend.git
          - git push --mirror git@github.com:kganapathi6008/hello-mrr.git
          