---
steps:

  - name: 'gcr.io/cloud-builders/docker'
    id: build
    waitFor: ['-']
    args: 
      - build 
      - -t
      - us-east1-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_FOLDER_NAME/$_IMAGE_NAME:$SHORT_SHA
      - .


  - name: 'gcr.io/cloud-builders/docker'
    id: push
    waitFor: ['build']
    args:
      - push
      - us-east1-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_FOLDER_NAME/$_IMAGE_NAME:$SHORT_SHA

  - name: 'gcr.io/cloud-builders/gcloud'
    id: updatelatesttag
    waitFor: ['push']
    args:
      - artifacts
      - docker
      - tags
      - add
      - us-east1-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_FOLDER_NAME/$_IMAGE_NAME:$SHORT_SHA 
      - us-east1-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_FOLDER_NAME/$_IMAGE_NAME:$_ARTIFACT_TAG_NAME
  
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    # id: 'Authorize Cloud Build'
    # waitFor: ['updatelatesttag']
    # entrypoint: 'bash'
    # args:
      # - -c
      # - |
        # apt-get install dnsutils -y &&
        # cloudbuild_external_ip=$(dig @resolver4.opendns.com myip.opendns.com +short) &&
        # gcloud container clusters update $_CLUSTER_NAME --region=$_REGION --enable-master-authorized-networks --master-authorized-networks $cloudbuild_external_ip/32 &&
        # echo $cloudbuild_external_ip  

  # - name: 'gcr.io/cloud-builders/kubectl'
    # id: deploy
    # waitFor: ['Authorize Cloud Build']
    # args:
      # - set
      # - image
      # - deployment
      # - $_SERVICE_NAME
      # - $_CONTAINER_NAME=us-east1-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_FOLDER_NAME/$_IMAGE_NAME:$SHORT_SHA
    # env:
      # - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      # - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    # id: 'Disable Authorized Networks'
    # waitFor: ['deploy']
    # entrypoint: 'gcloud'
    # args:
      # - 'container'
      # - 'clusters'
      # - 'update'
      # - '$_CLUSTER_NAME'
      # - '--region=$_REGION'
      # - '--no-enable-master-authorized-networks'



substitutions:
    _ARTIFACT_FOLDER_NAME: dev
    _IMAGE_NAME: nodejs-be
    _ARTIFACT_TAG_NAME: latest
    _REGION: us-east1-b
    _BRANCH_NAME: develop
    _CLUSTER_NAME: dev-cluster
    _SERVICE_NAME: nodejs-be
    _CONTAINER_NAME: nodejs-be

timeout: 1200s
